Proj 1 vector operations
BorisGorelov/made-cpp-2020-hw pull request #2
Opened 2020-10-06 21:36 UTC by BorisGorelov

Опоздал на полчаса в связи с тем, что новичок в использовании веток в гите. Прошу понять и простить. Также не успел реализовать два оператора, засиделся с hw3. Надеюсь, заслужил хотя бы несколько баллов.

2020-10-18 00:15 UTC, xterrafunny requested changes

2020-10-18 00:15 UTC, xterrafunny commented on simple_compose/src/main.cpp
> +}
Этого здесь быть не должно

2020-10-18 00:15 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +    if (v1.size() != v2.size()){
Отступ 2 пробела

2020-10-18 00:15 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +{
Фигурная скобка пишется на предыдущей строке

2020-10-18 00:15 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +        throw -1;
Ужасная практика

2020-10-18 00:15 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +    std::vector<double> buf;
Размер уже известен, зачем заставлять вектор расширяться

2020-10-18 00:15 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +    if (v1.size() != v2.size() && v1.size() != 3)
Странно писать здесь `&&`

2020-10-18 00:15 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +    if (v1.size() != v2.size()){
Нужен пробел перед фигурной скобкой

2020-10-18 00:15 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +namespace task {
Что?

2020-10-20 14:18 UTC, BorisGorelov commented on simple_compose/src/main.cpp
> +}
У меня есть вопрос. Подскажите на будущее, где лучше задавать вопросы: здесь, в дискорде со ссылкой на ПР или на портале в личных сообщениях? Итак, при сдаче я опирался на этот туториал https://www.youtube.com/watch?v=V388CewBwL8&feature=emb_title. В нем на 2:40 Константин делает pull и сразу же checkout в новую ветку. Вопрос, откуда она у него взялась? Я повторил эти действия, но у меня вытянутые изменения добавились в master, я сделал ПР с первой задачей (ее еще не проверяли, это ок?), затем опять сделал pull уже с этим проектом, по-этому здесь оказался этот код. Итак, я правильно понимаю, что перед pull мне надо было сделать git checkout <стартовый коммит>; git checkout -b <название новой ветки>; git pull origin <это же название ветки>? Если да, как Константину удалось обойти git checkout -b <..>? Ну и основной вопрос, чтобы исправить сейчас ситуацию, мне стоит удалить лишний код и сделать новый коммит, правильно?
Извините заранее за простыню и море вопросов, но очень хочется разобраться)

2020-10-26 22:39 UTC, Costello1329 approved these changes

2020-10-26 22:39 UTC, merged